### ISSUE TITLE
Timeout Error Not Captured

### ISSUE THREAD

**Issue by slactjohnson** [pcdshub/las-dispersion-scan#9]
## Expected Behavior
Timeout errors are captured

## Current Behavior
This is not the case. When using a stage with a tolerance set too small, the stage never reached the position and errored out. See error below:

`(pcds-5.6.0) [tjohnson@ctl-las-lln-02:~/trunk/las-dispersion-scan]$ ./run-lln.sh 
ERROR:las_dispersion_scan.utils:Failed to run <function DscanMain._start_scan.<locals>.scan at 0x7f8ab1f76af0>(*(), **{}) in thread pool
Traceback (most recent call last):
  File "/cds/home/t/tjohnson/trunk/las-dispersion-scan/las_dispersion_scan/utils.py", line 222, in run
    self.return_value = self.func(*self.args, **self.kwargs)
  File "/cds/home/t/tjohnson/trunk/las-dispersion-scan/las_dispersion_scan/widgets.py", line 789, in scan
    for point in self.scan.run(
  File "/cds/home/t/tjohnson/trunk/las-dispersion-scan/las_dispersion_scan/dscan.py", line 685, in run
    self.stage.set(setpoint).wait(timeout=timeout)
  File "/cds/group/pcds/pyps/apps/dev/pythonpath/ophyd/status.py", line 412, in wait
    raise WaitTimeoutError("Status has not completed yet.")
ophyd.utils.errors.WaitTimeoutError: Status has not completed yet.
`

**Comment by slactjohnson** [comment]
This is a slightly different issue that we see with the Elliptec, but related. Catching and attempting to correct the `WaitTimeoutError`s could help with the Elliptec problems.

**Comment by klauer** [comment]
Based on the line in the traceback, this timeout error is from the test PR in #16.

I'll update that branch, though it's unclear if we'll stick with that branch or work with the already-proven master branch implementation provided by @slactjohnson
